name: Build
on:
  push:
    # only branch pushes, not tags
    # ignore hlx branches
    branches-ignore:
      - 'hlx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "bla"
